# Lab 07
## Similarity measures

# <img src='1.png'>

In [1]:
import numpy as np
x=np.array([15,20,9,14])
y=np.array([14,18,7,10])

In [2]:
x

array([15, 20,  9, 14])

In [3]:
y

array([14, 18,  7, 10])

# Manhattan Distance

In [4]:
# |x1-y1|+|x2-y2|+|x3-y3|+|x4-y4|
m=0
D=np.arange(len(x))
for i in range(len(x)):
    D[i]=abs(x[i]-y[i])
    m=m+D[i]


In [5]:
m # Manhattan Distance

9

# Minkowski Distance

# <img src='2.PNG'>

In [6]:
def Lnorm(X,Y,r):
    sum=0
    for i in range(len(X)):
        sum=sum+(abs(X[i]-Y[i]))**r
    return pow(sum,1/r)    

In [7]:
Lnorm(x,y,1) # -> Manhattan

9.0

In [8]:
Lnorm(x,y,2) #-> Eucledian

5.0

In [9]:
Lnorm(x,y,3) # -> L3 norm

4.3267487109222245

# As Degree of Norm Increases-> Minkowski Distance Decreases 

# <img src='3.PNG'>

## 1. In information theory, the Hamming distance between two strings of equal length is the number of positions at which the corresponding symbols are different.

## 2. Jaccard Similarity is a statistic used for comparing the similarity and diversity of sample sets. The Jaccard coefficient measures similarity between finite sample sets, and is defined as the size of the intersection divided by the size of the union of the sample sets.

## 3. Cosine similarity is a measure of similarity between two non-zero vectors of an inner product space that measures the cosine of the angle between them. 

# <img src='4.PNG'>

In [10]:
# Hamming Distance
d=0
x=(0,1,0,1,0,1,0,0,0,1)
y=(0,1,0,0,0,1,1,0,0,0)
for i in range(len(x)):
    if x[i]!=y[i]:
        d=d+1
print('Hamming Distance is:',d)        
        

Hamming Distance is: 3


# <img src='5.PNG'>

In [11]:
# Jaccard Index
m11=m01=m10=0
for i in range(len(x)):
    if x[i]==1 and y[i]==1:
        m11=m11+1
    elif x[i]==0 and y[i]==1:
        m01=m01+1
    elif x[i]==1 and y[i]==0:
        m10=m10+1
        
J=m11/(m11+m10+m01)
print('Jaccard Coefficient=',J)

Jaccard Coefficient= 0.4


In [12]:
# Cosine Similarity
x=np.asarray(x)
y=np.asarray(y)

In [13]:
x

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1])

In [14]:
y

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0])

In [15]:
modx=Lnorm(x,np.zeros(len(x)),2)
mody=Lnorm(y,np.zeros(len(y)),2)
print(modx,' ',mody)

2.0   1.7320508075688772


In [16]:
cs=(np.dot(x,y))/modx*mody
print('Cosine Similarity is:',cs)

Cosine Similarity is: 1.7320508075688772


# <img src='6.PNG'>

# 1. For a, I think Jaccard Similarity is better, because it is the case of Recommendation where two items are compared based on their similarity.
# Jaccard Coefficient ignores (0,0) pairs which are of no use.

# 2.  For b, I think Cosine Similarity is better because when dot product is taken, the angle between 2 vectors is also taken into consideration . Whereas Eucledian distance would increase if we double the vectors, Cosine Similarity would still be same.

# <img src='7.PNG'>

In [17]:
A=['Health','Patient','Politics','Shah']
B=['Health','Gujarat','Tiger','Politics']
C=['Hardik','Patel','Politics']
print(A,B,C)

['Health', 'Patient', 'Politics', 'Shah'] ['Health', 'Gujarat', 'Tiger', 'Politics'] ['Hardik', 'Patel', 'Politics']


In [18]:
from functools import reduce
a=reduce(np.intersect1d, (A,B,C))
a

array(['Politics'], dtype='<U8')

In [19]:
intersect_all=len(a)
b=reduce(np.union1d, (A,B,C))
b

array(['Gujarat', 'Hardik', 'Health', 'Patel', 'Patient', 'Politics',
       'Shah', 'Tiger'], dtype='<U8')

In [20]:
union_all=len(b)

In [21]:
print('Jaccard Similarity among A,B,C is:',intersect_all/union_all)

Jaccard Similarity among A,B,C is: 0.125


# Three Applications of Jaccard Similarity of Documents:

# 1. Plagiarism: suppose we want check a document for Plagiarism. The problem can be solved by seeing the document in question is “similar” to any of document(s) in the repository.
# 2. A web crawler must be able to detect if the document is mirror of other document.
# 3. A news aggregator detecting that news article is same, but coming from different sources.

# <img src='8.PNG'>

In [35]:
import pandas as pd
data=pd.DataFrame(columns=['Pankaj','Mithesh'])
rows=['MPC','Sportsman','Watches','Earlyriser','Att','CPI']


# Finding out Cosine Similarity
## Denote yes->1 No->0

In [60]:
Pankaj=np.array([1,1,5,1,40,7.8])
Mithesh=np.array([1,0,10,0,60,6.9])

In [61]:
Pankaj

array([ 1. ,  1. ,  5. ,  1. , 40. ,  7.8])

In [62]:
Mithesh

array([ 1. ,  0. , 10. ,  0. , 60. ,  6.9])

In [63]:
modx=Lnorm(Pankaj,np.zeros(len(x)),2)
mody=Lnorm(Mithesh,np.zeros(len(y)),2)

In [64]:
modx

41.095498536944405

In [65]:
mody

61.22589321520757

In [66]:
np.dot(Pankaj,Mithesh)

2504.82

In [67]:
cs=(np.dot(Pankaj,Mithesh))/(modx*mody)
print('Cosine Similarity between Pankaj and Mithesh is:',cs)

Cosine Similarity between Pankaj and Mithesh is: 0.9955134666977309


# Collaborative Filtering

In [68]:
#make necesarry imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.metrics as metrics
import numpy as np
from sklearn.neighbors import NearestNeighbors
from scipy.spatial.distance import correlation, cosine
import ipywidgets as widgets
from IPython.display import display, clear_output
from sklearn.metrics import pairwise_distances
from sklearn.metrics import mean_squared_error
from math import sqrt
import sys, os
from contextlib import contextmanager

In [70]:
M = np.asarray([[1,1], 
                [1,0,],
               [5,10],
               [1,0],
               [40,60],
               [7.8,6.9]])
M=pd.DataFrame(M)
M

0     1
0   1.0   1.0
1   1.0   0.0
2   5.0  10.0
3   1.0   0.0
4  40.0  60.0
5   7.8   6.9

In [71]:
global k,metric
k=4
metric='cosine'

In [74]:
cosine_sim = 1-pairwise_distances(M, metric="cosine")
#Cosine similarity matrix
pd.DataFrame(cosine_sim)

0         1         2         3         4         5
0  1.000000  0.707107  0.948683  0.707107  0.980581  0.998131
1  0.707107  1.000000  0.447214  1.000000  0.554700  0.748997
2  0.948683  0.447214  1.000000  0.447214  0.992278  0.927586
3  0.707107  1.000000  0.447214  1.000000  0.554700  0.748997
4  0.980581  0.554700  0.992278  0.554700  1.000000  0.966763
5  0.998131  0.748997  0.927586  0.748997  0.966763  1.000000

In [76]:
#get pearson similarities for ratings matrix M
pearson_sim = 1-pairwise_distances(M, metric="correlation")
pd.DataFrame(pearson_sim)

0    1    2    3    4    5
0  1.0  NaN  NaN  NaN  NaN  NaN
1  NaN  1.0 -1.0  1.0 -1.0  1.0
2  NaN -1.0  1.0 -1.0  1.0 -1.0
3  NaN  1.0 -1.0  1.0 -1.0  1.0
4  NaN -1.0  1.0 -1.0  1.0 -1.0
5  NaN  1.0 -1.0  1.0 -1.0  1.0

In [82]:
#This function finds k similar users given the user_id and ratings matrix M
#Note that the similarities are same as obtained via using pairwise_distances
def findksimilarusers(user_id, ratings, metric = metric, k=k):
    similarities=[]
    indices=[]
    model_knn = NearestNeighbors(metric = metric, algorithm = 'brute') 
    model_knn.fit(ratings)

    distances, indices = model_knn.kneighbors(ratings.iloc[user_id-1, :].values.reshape(1, -1), n_neighbors = k+1)
    similarities = 1-distances.flatten()
    print('{0} most similar users for User {1}:\n'.format(k,user_id))
    for i in range(0, len(indices.flatten())):
        if indices.flatten()[i]+1 == user_id:
            continue;

        else:
            print('{0}: User {1}, with similarity of {2}'.format(i, indices.flatten()[i]+1, similarities.flatten()[i]))
            
    return similarities,indices